import dotenv from 'dotenv'
dotenv.config()

export const D_DEFAULT_USER_ROLE_NAME = process.env.DEFAULT_USER
export const D_SUPER_USER_ROLE_NAME = process.env.SUPER_USER
export const D_DEFAULT_USER_ACCOUNT_NAME = 'Abdelhady'
export const D_DEFAULT_USER_ACCOUNT_PASSWORD = '123'
export const D_DEFAULT_AVATAR_PATH = process.env.AVATAR_STORAGE_PATH
export const D_DEFAULT_ATTACHMENTS_PATH = process.env.ATTACHMENTS_STORAGE_PATH
export const D_DEFAULT_MAX_ATTACHMENTS = parseFloat(process.env.MAX_ATTACHMENTS)

export const D_USER_PERM = {
    GET_ALL: 'GET_ALL_USERS',
    GET: 'GET_USER',
    CREATE: 'CREATE_USER',
    UPDATE: 'UPDATE_USER',
    DELETE: 'DELETE_USER',
    GET_POSTS: 'GET_USER_POSTS',
    CREATE_POST: 'CREATE_USER_POST',
    UPDATE_POST: 'UPDATE_USER_POST',
    DELETE_POST: 'DELETE_USER_POST',
    GET_REPLIES: 'GET_USER_REPLIES',
    CREATE_REPLY: 'CREATE_USER_REPLY',
    UPDATE_REPLY: 'UPDATE_USER_REPLY',
    DELETE_REPLY: 'DELETE_USER_REPLY',
    GET_ROLES: 'GET_USER_ROLES',
    CREATE_ROLE: 'CREATE_USER_ROLE',
    DELETE_ROLE: 'DELETE_USER_ROLE',
    GET_REACTIONS: 'GET_USER_REACTIONS',
    CREATE_REACTION: 'CREATE_USER_REACTION',
    DELETE_REACTION: 'DELETE_USER_REACTION',
    GET_TAGS: 'GET_USER_TAGS',
    CREATE_TAG: 'CREATE_USER_TAG',
    DELETE_TAG: 'DELETE_USER_TAG',
}

export const D_MESSAGE_PERM = {
    GET_ALL: 'GET_ALL_MESSAGES',
    GET: 'GET_MESSAGE',
    CREATE: 'CREATE_MESSAGE',
    UPDATE: 'UPDATE_MESSAGE',
    DELETE: 'DELETE_MESSAGE',
    GET_POSTS: 'GET_MESSAGE_POSTS',
    GET_POST: 'GET_MESSAGE_POST',
    UPDATE_POST: 'UPDATE_MESSAGE_POST',
    DELETE_POST: 'DELETE_MESSAGE_POST',
    GET_REPLIES: 'GET_MESSAGE_REPLIES',
    GET_REPLY: 'GET_MESSAGE_REPLY',
    DELETE_REPLY: 'DELETE_MESSAGE_REPLY',
    GET_REACTIONS: 'GET_MESSAGE_REACTIONS',
    DELETE_REACTION: 'DELETE_MESSAGE_REACTION',
    GET_TAGS: 'GET_MESSAGE_TAGS',
    CREATE_TAG: 'CREATE_MESSAGE_TAG',
    DELETE_TAG: 'DELETE_MESSAGE_TAG',
}

export const D_ROLE_PERM = {
    GET_ALL: 'GET_ALL_ROLES',
    GET: 'GET_ROLE',
    CREATE: 'CREATE_ROLE',
    UPDATE: 'UPDATE_ROLE',
    DELETE: 'DELETE_ROLE',
    GET_PERMISSIONS: 'GET_ROLE_PERMISISONS',
    CREATE_PERMISSION: 'CREATE_ROLE_PERMISSION',
    DELETE_PERMISSION: 'DELETE_ROLE_PERMISSION',
}

export const D_PERMISSION_PERM = {
    GET_ALL: 'GET_ALL_PERMISSIONS',
    GET: 'GET_PERMISSION',
    CREATE: 'CREATE_PERMISSION',
    UPDATE: 'UPDATE_PERMISSION',
    DELETE: 'DELETE_PERMISSION',
    GET_ROLES: 'GET_PERMISSION_ROLES',
}

export const D_TAG_PERM = {
    GET_ALL: 'GET_ALL_TAGS',
    GET: 'GET_TAG',
    CREATE: 'CREATE_TAG',
    UPDATE: 'UPDATE_TAG',
    DELETE: 'DELETE_TAG',
    GET_MESSAGES: 'GET_TAG_MESSAGES',
}

export const D_REACTION_PERM = {
    GET_ALL: 'GET_ALL_REACTIONS',
    GET: 'GET_REACTION',
    CREATE: 'CREATE_REACTION',
    UPDATE: 'UPDATE_REACTION',
    DELETE: 'DELETE_REACTION',
    GET_MESSAGES: 'GET_REACTION_MESSAGES',
}

export const D_LOG_PERM = {
    GET_ALL: 'GET_ALL_LOGS',
    GET: 'GET_LOG',
    CREATE: 'CREATE_LOG',
    UPDATE: 'UPDATE_LOG',
    DELETE: 'DELETE_LOG',
}

export const D_ATTACHMENT_PERM = {
    GET_ALL: 'GET_ALL_ATTACHMENTS',
    GET: 'GET_ATTACHMENT',
    CREATE: 'CREATE_ATTACHMENT',
    UPDATE: 'UPDATE_ATTACHMENT',
    DELETE: 'DELETE_ATTACHMENT',
}

export const D_DEFAULT_PERM = {
    GET_USERS: D_USER_PERM.GET_ALL,
    GET_USER: D_USER_PERM.GET,
    UPDATE_USER: D_USER_PERM.UPDATE,
    GET_USER_POSTS: D_USER_PERM.GET_POSTS,
    CREATE_USER_POST: D_USER_PERM.CREATE_POST,
    UPDATE_USER_POST: D_USER_PERM.UPDATE_POST,
    DELETE_USER_POST: D_USER_PERM.DELETE_POST,
    GET_USER_REPLIES: D_USER_PERM.GET_REPLIES,
    CREATE_USER_REPLY: D_USER_PERM.CREATE_REPLY,
    UPDATE_USER_REPLY: D_USER_PERM.UPDATE_REPLY,
    DELETE_USER_REPLY: D_USER_PERM.DELETE_REPLY,
    GET_USER_ROLES: D_USER_PERM.GET_ROLES,
    GET_USER_REACTIONS: D_USER_PERM.GET_REACTIONS,
    CREATE_USER_REACTION: D_USER_PERM.CREATE_REACTION,
    DELETE_USER_REACTION: D_USER_PERM.DELETE_REACTION,
    GET_USER_TAGS: D_USER_PERM.GET_TAGS,
    CREATE_USER_TAG: D_USER_PERM.CREATE_TAG,
    DELETE_USER_TAG: D_USER_PERM.DELETE_TAG,
    GET_MESSAGES: D_MESSAGE_PERM.GET_ALL,
    GET_MESSAGE: D_MESSAGE_PERM.GET,
    GET_MESSAGE_POSTS: D_MESSAGE_PERM.GET_POSTS,
    GET_MESSAGE_REPLIES: D_MESSAGE_PERM.GET_REPLIES,
    GET_MESSAGE_REACTIONS: D_MESSAGE_PERM.GET_REACTIONS,
    GET_MESSAGE_TAGS: D_MESSAGE_PERM.GET_TAGS,
    CREATE_MESSAGE_TAG: D_MESSAGE_PERM.CREATE_TAG,
    DELETE_MESSAGE_TAG: D_MESSAGE_PERM.DELETE_TAG,
    GET_TAGS: D_TAG_PERM.GET_ALL,
    GET_TAG: D_TAG_PERM.GET,
    GET_REACTIONS: D_REACTION_PERM.GET_ALL,
    GET_REACTION: D_REACTION_PERM.GET,
    GET_ATTACHMENT: D_ATTACHMENT_PERM.GET,
    DELETE_ATTACHMENT: D_ATTACHMENT_PERM.DELETE,
}

export const D_DEFAULT_REACTIONS = [
    { Name: 'Like', Points: 1 },
    { Name: 'Love', Points: 2 },
    { Name: 'Confused', Points: 1 },
    { Name: 'Sad', Points: 1 },
]